### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by okj203** [SamuelSacco/SamCloud#2]
- [ ] Comments entity needs to be included in the sample state
- [ ] Likes entity needs to be included in the sample state
- [ ] Sample state is part of frontend, use camelCase
- [ ] Playlists entity needs a table
- [ ] Albums entity needs a table
- [ ] The frontend routes page in wiki needs more info. Please refer to [this link to a sample frontend routes page.](https://github.com/appacademy/2021-04-19-NYC-Lecture-Notes/wiki/Front-End-Routes-&-Components)
